POST http://localhost:5000/api/email-lookup
Content-Type: application/json

{
    "email": "gyanprakash2483@gmail.com"
}

###

POST http://localhost:5000/api/phone-lookup
Content-Type: application/json

{
    "phone": "+91 9876543210"
}

###

POST http://localhost:5000/api/sherlock
Content-Type: application/json

{
    "usernames": ["test"]
}

###

POST http://localhost:5000/api/maigret
Content-Type: application/json

{
    "username": "GyanPrakash2483"
}

###

POST http://localhost:5000/api/dork-lookup
Content-Type: application/json

{
    "phone": "8956487968",
    "email": "gyan@email.com",
    "username": "gyanprakash____"
}

###

POST http://localhost:5000/api/socialscan
Content-Type: application/json

{
    "username": "Dream"
}